### ISSUE TITLE
Replanning discussion

### ISSUE THREAD

**Issue by rafael1193** [fire-rs-laas/fire-rs-saop#14]
I started hacking some re-planning capability. In bf41acba220d5de169a4ca24fd96ae8db750c5f9 ```Planner``` gets a ```replan``` function that modifies the planning parameters to start the UAVs a certain later time. This time is always adjusted to the start time of some segment because of. Environment conditions can also be changed (wind is the key variable here).

Next steps should be:
 - Restart at any plan time 't'.
 - Restart at any position. 

Current problems:
 - There is not track of previous observations, so the planner can make the drones explore some area that is already known.

**Comment by arbimo** [comment]
Here are some thoughts on replanning.

Given a plan, executing it results in its modification : at the minimum, the start/end time of all executed maneuvers are instantiated to their true value instead of being computed. This might result in the plan invalidation, for instance if it becomes to long.

There are essentially to options for handling this kind of things : we can keep track of the history in a separated data structure and ask for replanning from the current time on.
Or we can refine/constrain an existing plan.

The latest option is the one I would prefer because it allows reusing the same framework for checking plan validity in an incremental way. In its simplest form it would require : 
 - refine a plan based on its execution. In our case it would mean updating the maneuvers with what actually got executed (in space and time). This should be easy to do but requires some modification so that timestamps are not necessarily recomputed from the global start.
 - inform VNS of what is the part of the plan that can be modified (i.e. what is in the future). A trajectory currently has a "first_modifiable" field that was introduced for this purpose.
 - allow VNS to start from an invalid plan. To start with this can be done by shuffling the invalid plan.

Important to keep in mind is that VNS (or local search in general) allows to repair an invalid plan or optimize an existing one.

**Comment by rafael1193** [comment]
Thanks for the comments.

The code that I merged recently on master restarts the planning from some time _t_ -- updating of course the remaining flight time -- and takes in account which cells-time have been observed (either with fire or not).  

I agree refining the plan is the way to go.

**Comment by rafael1193** [comment]
Just an update about replanning.

There is already implemented a replanning strategy that works quite well. It is based on your suggestions: It takes an existing plan and tags past maneuvers as not modifiable. Then it resumes planning refining this plan. 
 
/python/fire_rs/planning/demo_replanning.py shows this capability

There is no option to resume from a invalid plan, but this shouldn't be a problem. As the planning algorithm always produces valid plans, we don't need to repair them.
