### ISSUE TITLE
Question: What's the best way to launch everything?

### ISSUE THREAD

**Issue by andrewjong** [fire-rs-laas/fire-rs-saop#19]
Hi Rafael, thanks for the chat yesterday!

What's the best way to launch the sim and everything to reproduce what's in the thesis?

- There is a `main.py` in the project root---that seems to only simulate fire ignition on a 2D plot.
- There are the `make` targets as documented in the readme. However, `make benchmark` seems to not produce any output. And the test targets seem to only be unit testing the API.
- Is the correct starting location the supersaop ROS package? There is no ROS installed in the docker image, so I'm assuming I'll have to install it first. What would be a good launch command to use (any args needed to be passed)?

Would greatly appreciate the clarification. Thank you!

**Comment by rafael1193** [comment]
Hi Andrew, 

`main.py` is not actually a real _main_ file :( The closest thing to a typical _main_ is `benchmark.py` but there are many scripts starting with "demo_" that you can check out (e.g. https://github.com/laas/fire-rs-saop/blob/master/python/fire_rs/planning/demo_replanning.py) Each of them shows some particular feature we were in need to test! (Some of them work better than others)

`make benchmark` is supposed to run `benchmark.py` generating a fire scenario, runnning multiple planning instances over it and producing pictures of the result. Lines 157 to 255 of python/fire_rs/planning/benchmark.py show how that is done.

In order to execute it manually, first you need to set the FIRERS_DATA (to the _fire-rs-data/porto_utm/10m/_ dataset) and WINDNINJA_CLI_PATH as indicated in the README. Then you can execute:

`python3 -m fire_rs.planning.benchmark create default ./my_scenario_folder`

and

`python3 -m fire_rs.planning.benchmark run ./my_scenario_folder`

ROS and supersaop were not included into the docker image because there were many downsides: no possibility to have the GUI, or morse, and no communication with the UAV software. The way I was using it was by launching 
fire-rs-saop/supersaop/launch/supersaop.launch and then the scenario I wanted e.g. porto_utm.launch. However it won't work out of the box because you need an instance of Dune and Neptus running alongside supersaop...

I hope this explanation is able to help you out with saop!
