### ISSUE TITLE
Dubins 3D does not respect triangular inequalities

### ISSUE THREAD

**Issue by arbimo** [fire-rs-laas/fire-rs-saop#2]
Current workaround (04f46f31f4ab65f97095b9b340b9fd682b6fb6a7) is to revert to Dubins 2D

**Comment by rafael1193** [comment]
I've trying to identify the source of the problem. What I have discovered for now is that the inequality is respected for all the low-altitude and medium-altitude paths, and not respected for some high altitude paths (e2037f6)

**Comment by rafael1193** [comment]
I tested the dubins3d code for the high altitude case thoroughly. I discovered, and solved, just one bug (https://github.com/fire-rs-laas/fire-rs-saop/commit/f3eb60ae2bda9d000d631c0e347dd12c2915a9c0), that doesn't make any change in the alleged triangular inequality bug.
I reviewed the literature in which the dubins3d code is based on [1] [2] and, in fact, this is not a bug but an expected behavior.

When requesting the UAV to do a high-altitude or medium-altitude maneuver, the path has to be extended somewhat because just climbing a the maximum rate (ɣ̅) is not enough. This means that the path length is determined by increment in height, so every trajectory belonging to the maneuver types mentioned previously has the same length. For high-altitude maneuvers, this length is L_path(R*) such that 

    (L_path(R*) + 2kπR*)×tan(ɣ̅) = Δz 

where k is an integer number of full turns. For medium-altitude maneuvers, the trajectory is extended by a adding a new turn before or after the 2D Dubins path.


[1] H. Chitsaz and S. M. LaValle, “Time-optimal paths for a Dubins airplane,” in 2007 46th IEEE Conference on Decision and Control, 2007, pp. 2379–2384.
[2] M. Owen, R. W. Beard, and T. W. McLain, “Implementing Dubins Airplane Paths on Fixed-Wing UAVs,” in Handbook of Unmanned Aerial Vehicles, K. P. Valavanis and G. J. Vachtsevanos, Eds. Springer Netherlands, 2015, pp. 1677–1701.

**Comment by arbimo** [comment]
I have not looked at the papers in depth but If the triangle inequality is not respected, it means that the computed paths are not optimal; which is strange given the title of the first paper ^^

Even if the path are not provably optimal, they should be close enough:
 - it should be very hard to find a point B such that  len(A->C) > len(A->B->C)
 - even with such a point, a detour by B should not significantly reduce the length of the path.

From my tests, it seemed that this was not the case and could significantly alter the algorithm output.
Note that I might have been misled as I thought we were still considering planar trajectories computed through Dubins3D.
I'll try to validate this with more unit tests using randomly generated points.

**Comment by rafael1193** [comment]
For the high altitude case, quoting from [1], "In that case, uθ can have any value within [-1, 1], by (8). This means that the projection of q(t) _[q(t) being the function that gives the position at any time]_ onto the (x,y,θ)-space can be any feasible path for the dubins car. However, the length of such path must be |Δz|"

From what I understand this means that the length of any path from a point A to a sufficiently high point C is only given by Δz. As uθ is free, I can make the path to pass by B, (if A->B and B->C are high-altitude) keeping the same path length. 

In theory we should get Dubins(A->B) + Dubins(B->C) = Dubins(A->C), but in the real, imprecise, world they mismatch a bit.

Given

```c++
Waypoint3d a {0, 0, 0, 0};
Waypoint3d b {100, 100, 500, M_PI_2};
Waypoint3d c {200, 100, 1000, M_PI};
```
and setting in ```struct Dubins3dPathLength```
```c++
const double TOLERANCE = 0.0001;
```

```Dubins(A->B)``` gives me 5008.35m + ```Dubins(B->C)``` 5008.34m  = 10016.69m and ```Dubins(A->C)``` is 10016,68m (an error of 1cm over a 10km path)

**Comment by arbimo** [comment]
Yes, I would expect the distance of 3D dubins to be the max of \delta_z and the dubins 2D distance. But there might some corner cases I am not seeing.

I have updated the runtime assertions for triangular inequalities in (5fea5b9061ab8d8688df3785d96a835474b048a2). Rounding errors should not trigger them anymore.
